gazebo:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 200

  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: J1_JOINT
    pid: {p: 100.0, i: 0.01, d: 5.0}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: J2_JOINT
    pid: {p: 100.0, i: 0.01, d: 5.0}
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: J3_JOINT
    pid: {p: 100.0, i: 0.01, d: 5.0}
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: J4_JOINT
    pid: {p: 100.0, i: 0.01, d: 5.0}
  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: J5_JOINT
    pid: {p: 100.0, i: 0.01, d: 5.0}
  # joint6_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: J6_JOINT
    # pid: {p: 100.0, i: 0.01, d: 5.0}
  # joint7_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: J1_JOINT
    # pid: {p: 100, i: 0.001, d: 10.0}
  # joint8_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: J1_JOINT
    # pid: {p: 100, i: 0.001, d: 10.0}
  # gazebo_ros_control:
  #   pid_gains:
  #     joint1:
  #       p: 100.0
  #       i: 0.01
  #       d: 1.0
  #     joint2:
  #       p: 100.0
  #       i: 0.01
  #       d: 1.0
  #     joint3:
  #       p: 100.0
  #       i: 0.01
  #       d: 1.0
  #     joint5:
  #       p: 100.0
  #       i: 0.01
  #       d: 1.0

